### ISSUE TITLE
Ant Design Styling for ReactJs

### ISSUE THREAD

**Issue by furkanuyanik** [BzenkoSergey/ng-cron#80]
![image](https://user-images.githubusercontent.com/51247701/152334489-f987e929-0c56-40fb-9d83-1c6eec861d19.png)

Hi, thank you very much for creating such a library.

I am using Ant Design as React UI Framework in my project. But my project becomes unusable because Bootstrap conflicts with Ant Design.

Are you going to develop for Ant Design?

**Comment by dimadev01** [comment]
Hey! I'm using Ant Design 3. What I did is manually copied some styles and at least I'm pretty happy about how it ended up looking

```css
.cron {
  .nav {
    display: flex;
    flex-wrap: wrap;
    padding-left: 0;
    margin-bottom: 0;
    list-style: none;
  }

  .nav-link {
    display: block;
    padding: 8px 16px;
    color: #0d6efd;
    text-decoration: none;
    transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,
      border-color 0.15s ease-in-out;
  }
  @media (prefers-reduced-motion: reduce) {
    .nav-link {
      transition: none;
    }
  }
  .nav-link:hover,
  .nav-link:focus {
    color: #0a58ca;
  }
  .nav-link.disabled {
    color: #6c757d;
    pointer-events: none;
    cursor: default;
  }

  .nav-tabs {
    border-bottom: 1px solid #dee2e6;
  }
  .nav-tabs .nav-link {
    margin-bottom: -1px;
    background: none;
    border: 1px solid transparent;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
  }
  .nav-tabs .nav-link:hover,
  .nav-tabs .nav-link:focus {
    border-color: #e9ecef #e9ecef #dee2e6;
    isolation: isolate;
  }
  .nav-tabs .nav-link.disabled {
    color: #6c757d;
    background-color: transparent;
    border-color: transparent;
  }
  .nav-tabs .nav-link.active,
  .nav-tabs .nav-item.show .nav-link {
    color: #495057;
    background-color: #fff;
    border-color: #dee2e6 #dee2e6 #fff;
  }
  .nav-tabs .dropdown-menu {
    margin-top: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .nav-pills .nav-link {
    background: none;
    border: 0;
    border-radius: 4px;
  }
  .nav-pills .nav-link.active,
  .nav-pills .show > .nav-link {
    color: #fff;
    background-color: #0d6efd;
  }

  .nav-fill > .nav-link,
  .nav-fill .nav-item {
    flex: 1 1 auto;
    text-align: center;
  }

  .nav-justified > .nav-link,
  .nav-justified .nav-item {
    flex-basis: 0;
    flex-grow: 1;
    text-align: center;
  }

  .nav-fill .nav-item .nav-link,
  .nav-justified .nav-item .nav-link {
    width: 100%;
  }

  .c-tab-content {
    border-bottom: 1px solid #dee2e6;
    border-left: 1px solid #dee2e6;
    border-right: 1px solid #dee2e6;
    padding: 15px;
  }

  .form-group {
    margin-bottom: 16px;
  }

  .form-check {
    position: relative;
    display: block;
    padding-left: 20px;
  }

  .form-check-input {
    position: absolute;
    margin-top: 4px;
    margin-left: -20px;
  }

  .form-check-label {
    margin-bottom: 0;
  }

  .form-control {
    display: block;
    width: 100%;
    height: calc(36px + 2px);
    padding: 6px 12px;
    font-size: 16px;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 4px;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }

  .form-control-sm {
    height: calc(30px + 2px);
    padding: 4px 8px;
    font-size: 14px;
    line-height: 1.5;
    border-radius: 2.5px;
  }

  .ml-1,
  .mx-1 {
    margin-left: 4px !important;
  }

  .mr-1,
  .mx-1 {
    margin-right: 4px !important;
  }

  .pt-1 {
    padding-top: 4px !important;
  }

  .pl-3 {
    padding-left: 16px !important;
  }

  .row {
    display: flex;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px;
  }

  .col-1 {
    position: relative;
    width: 100%;
    padding-right: 15px;
    padding-left: 15px;
    flex: 0 0 8.333333%;
    max-width: 8.333333%;
  }

  .col-2 {
    position: relative;
    width: 100%;
    padding-right: 15px;
    padding-left: 15px;
    flex: 0 0 16.666667%;
    max-width: 16.666667%;
  }

  .form-inline {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-flow: row wrap;
    flex-flow: row wrap;
    -ms-flex-align: center;
    align-items: center;

    @media (min-width: 576px) {
      .form-check {
        display: flex;
        align-items: center;
        justify-content: center;
        width: auto;
        padding-left: 0;
      }

      .form-control {
        display: inline-block;
        width: auto;
        vertical-align: middle;
      }
    }

    .form-control:disabled {
      background-color: #e9ecef;
      opacity: 1;
    }

    .form-check-input {
      position: relative;
      margin-top: 0;
      margin-right: 4px;
      margin-left: 0;
    }

    label {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 0;
    }
  }
}
```

![CleanShot 2022-04-01 at 4 48 30](https://user-images.githubusercontent.com/7450379/161331774-2a558cc2-2bdd-4510-9de2-01f980cff634.png)
